services:
  # Reload Caddy config: docker compose exec -w /etc/caddy caddy caddy reload
  reverse-proxy:
    image: caddy:2-alpine
    restart: unless-stopped
    cap_add: # Comment out if running on Windows
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/server/caddy:/etc/caddy
      - caddy_data:/data
  web:
    extends:
      file: docker-compose.yaml
      service: web
    ports: !reset []
    depends_on:
      reverse-proxy:
        condition: service_started

volumes:
  caddy_data:
