# TODO: Docker Compose development setup
services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    image: !reset null
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
  worker:
    extends:
      file: docker-compose.yml
      service: worker
    image: !reset null
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - 5432:5432
    env_file:
      - ./server/env/development.env

volumes:
  db_data:
