services:
  match_uploader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
     - ./server/settings:/home/node/app/server/settings
     - ./server/videos:/home/node/app/server/videos
