<template>
  <VAlert v-if="!!matchStore.descriptionFetchError"
          color="error"
          variant="tonal"
          class="mb-4"
  >
    {{ matchStore.descriptionFetchError }}
  </VAlert>
  <div v-if="matchStore.selectedMatchKey">
    <VBtn class="mb-4"
          variant="outlined"
          prepend-icon="mdi-refresh"
          :loading="matchStore.descriptionLoading"
          :disabled="matchStore.uploadInProgress"
          @click="matchStore.getSuggestedDescription()"
    >
      Regenerate description
    </VBtn>
    <VAlert class="mb-4">
      If you edit the description now, it'll only apply to the current match's videos. To revert your changes, press
      <strong>Regenerate description</strong> above.
    </VAlert>
    <VTextarea v-model="matchStore.description"
               label="Description"
               :disabled="!matchStore.selectedMatchKey || matchStore.uploadInProgress || matchStore.descriptionLoading"
               messages="Raw YouTube video description. Generated by server when you select a match."
               :rules="[() => !!matchStore.description || 'Video description is required']"
               auto-grow
               class="mb-4"
    />
  </div>
  <VAlert v-else
          variant="tonal"
          class="mb-4"
  >
    <p>
      A custom description is generated for each match's videos using the template defined in
      <RouterLink to="/settings">Settings</RouterLink>. You'll see a preview here after you select a match above.
    </p>
  </VAlert>
</template>
<script lang="ts" setup>
import {useMatchStore} from "@/stores/match";

const matchStore = useMatchStore();
</script>
