<template>
  <VAlert v-if="!!matchStore.descriptionFetchError"
          color="error"
          class="mb-4"
  >
    {{ matchStore.descriptionFetchError }}
  </VAlert>
  <VBtn v-if="matchStore.selectedMatchKey"
        class="mb-4"
        variant="outlined"
        prepend-icon="mdi-refresh"
        :loading="matchStore.descriptionLoading"
        :disabled="matchStore.uploadInProgress"
        @click="matchStore.getSuggestedDescription()"
  >
    Regenerate description
  </VBtn>
  <VAlert v-else
          color="warning"
          variant="tonal"
          class="mb-4"
  >
    Careful! If you enter a description before selecting a match, it will be overwritten by the
    auto-generated description.
  </VAlert>
  <VTextarea v-model="matchStore.description"
             label="Description"
             :disabled="matchStore.uploadInProgress || matchStore.descriptionLoading"
             messages="Raw YouTube video description. Generated by server when you select a match."
             auto-grow
             class="mb-4"
  />
</template>
<script lang="ts" setup>
import {useMatchStore} from "@/stores/match";

const matchStore = useMatchStore();
</script>
