<!--FIXME update match uploads to use this component-->
<template>
  <VAlert
    v-if="!!error"
    color="error"
    variant="tonal"
    class="mb-4"
  >
    {{ error }}
  </VAlert>
  <div v-if="showInput">
    <VBtn
      class="mb-4"
      variant="outlined"
      prepend-icon="mdi-refresh"
      :loading="loading"
      :disabled="inputDisabled"
      @click="onRefreshDescription"
    >
      Regenerate description
    </VBtn>
    <VAlert class="mb-4">
      Changes you make to the description here will only apply to the current set of videos. To revert your changes, press
      <strong>Regenerate description</strong> above.
    </VAlert>
    <VTextarea
      v-model="description"
      label="Description"
      :disabled="inputDisabled || loading"
      messages="Raw YouTube video description. Generated by server."
      :rules="[() => !!description || 'Video description is required']"
      auto-grow
      class="mb-4"
    />
  </div>
  <VAlert
    v-else
    variant="tonal"
    class="mb-4"
  >
    <p>
      Descriptions are generated using the template defined in
      <RouterLink to="/settings">Settings</RouterLink>. After the description is generated for the current set of
      videos, you'll see a preview here.
    </p>
  </VAlert>
</template>
<script lang="ts" setup>
const description = defineModel<string | null>({
  default: null,
});

const emit = defineEmits<{
  onRefreshDescription: [];
}>();

defineProps<{
  error: string | null;
  showInput?: boolean;
  loading?: boolean;
  inputDisabled?: boolean;
}>();

function onRefreshDescription() {
  emit("onRefreshDescription");
}
</script>
