name: ci

on:
  pull_request:
    branches: [ "main" ]

jobs:
  server_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: yarn install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile
        dir: server
    - name: Run ESLint
      uses: github/super-linter/slim@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main
        IGNORE_GITIGNORED_FILES: true
        LINTER_RULES_PATH: server
        JAVASCRIPT_ES_CONFIG_FILE: $GITHUB_WORKSPACE/server/.eslintrc.yml
        FILTER_REGEX_INCLUDE: .*server/src/.*\.ts
        
  client_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: yarn install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile
        dir: client
        
  build_client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: yarn install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile
        dir: client
    - name: build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
        dir: client
