name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  build_release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      - name: Audit npm signatures
        run: npm audit signatures
        # Uncomment if trying ARM Docker builds again
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64 # ,linux/arm64 (temporarily disable ARM builds: https://github.com/nodejs/docker-node/issues/1335#issuecomment-1551547206 might help)
          push: false
          tags: |
            gafirst/match-uploader:latest
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run
